---
# Ansible playbook

- hosts: all
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: Copy public SSH key to remote temp location
      copy: src=files/your_ssh_public_key dest=/tmp/public_key mode=0644

    - name: Copy contents of public SSH key to authorized keys file
      shell: cat /tmp/public_key >> /home/vagrant/.ssh/authorized_keys
 
